# -*- coding: utf-8 -*-
"""Config do servico basement-finishing (Kevin 2026-10-06) para build_local_pages.py.

Onda 1: so cidades SEM pagina de basement da Wolf Carpenters ou da Innov Builders
(Wolf tem basement em Andover, Beverly, Boxford, Danvers, Hamilton, Lynn, Marblehead, Melrose,
Middleton, Nahant, North Andover, Peabody, Reading, Salem, Saugus, Swampscott, Wakefield, Wenham;
Innov tem Lynnfield, North Reading, Reading, Wakefield, Woburn). Nao adicionar essas cidades.
Placeholders validos: {City} {County} {constraint} {permit_authority} {permit_line}.
"""

CITIES = ['tewksbury', 'essex', 'weston', 'wilmington', 'carlisle', 'ipswich', 'groveland',
          'gloucester', 'winchester', 'georgetown']


def basement_cfg(BASE_URL):
    return {
        'slug': 'basement-finishing',
        'label': 'Basement Finishing',
        'cities': CITIES,
        'updated': 'October 2026',
        'title': 'Basement Finishing {City} MA | Free Estimate | DeFaria',
        'meta': 'Basement finishing in {City}, MA: moisture control, insulation, egress and finish by an owner-led local team. Real 2026 costs, free estimate.',
        'schema_name': '{City} basement finishing',
        'bc2_name': 'Basement Finishing',
        'bc2_url': BASE_URL + '/pages/finish-basements/',
        'eyebrow': 'Basement finishing in {City}, MA',
        'h1': 'Basement finishing {City} MA homeowners can live in, from moisture check to move-in',
        'lead': 'Basement finishing in {City} with DeFaria Construction turns an unfinished lower level into dry, warm, permitted living space, planned for {County} County homes and permitted through the {permit_authority}.',
        'hero_alt': 'Basement finishing in {City}, MA by DeFaria Construction',
        'hero_img': 'finish-basements-hero.webp',
        'top_video': ('qlDWpUeuiBg', 'From open framing to a finished, insulated room',
                      'Watch a DeFaria conversion go from bare studs to an insulated, drywalled and painted room. A {City} basement follows the same sequence, with moisture control first.'),
        'focus_h2': 'A {City} basement starts with the walls you cannot see.',
        'focus_tail': 'A finished basement in {City} only lasts if moisture, insulation and air sealing are handled before the first stud goes up, so the room stays dry and warm through a New England winter.',
        'focus_p2': 'This page is for {City} homeowners comparing basement finishing contractors. It covers local homes, real 2026 costs, permits, egress and the full process, with a direct path to a free estimate.',
        'cost_h2': 'How much does basement finishing cost in {City}?',
        'cost_answer_variants': [
            'Basement finishing in {City} usually runs about $35 to $90 per square foot, so a typical 700 to 900 square foot basement lands roughly between $30,000 and $75,000. Moisture work, a bathroom or an egress window move it up.',
            'Most {City} basements finish between $30,000 and $75,000 for 700 to 900 square feet, or about $35 to $90 per square foot, depending on what the space needs before the finish work starts.',
            'Plan on roughly $35 to $90 per square foot for a {City} basement, which puts a typical 700 to 900 square foot project around $30,000 to $75,000 before upgrades like a bathroom or a wet bar.',
        ],
        'cost_factors_variants': [
            ['Moisture control or drainage work before framing.',
             'Ceiling height and ducts or beams that need soffits.',
             'A bathroom, wet bar or kitchenette below grade.',
             'An egress window for a bedroom or office.'],
            ['The condition of the foundation and how dry it stays.',
             'Plumbing below the floor and whether an ejector pump is needed.',
             'Bedrooms that require egress windows and wells.',
             'Flooring, built-ins and finish level.'],
            ['Size of the space and number of rooms.',
             'Waterproofing, sump or dehumidification needs.',
             'Electrical panel capacity and lighting plan.',
             'Bathrooms, bars and custom carpentry.'],
        ],
        'cost_close': 'DeFaria gives a fixed, itemized {City} estimate at the walkthrough, so the price follows the real basement instead of a per-foot guess.',
        'process_h2': 'How a {City} basement project runs, step by step',
        'process_intro_variants': [
            'Most {City} basements follow the same clear sequence, so you always know what comes next.',
            'Every {City} basement moves through set phases, from the moisture check to the final walkthrough.',
            'A {City} basement is built in a fixed order, and each phase is inspected before the next one starts.',
        ],
        'process_steps_variants': [
            ['Walkthrough, measurements, moisture check and a fixed estimate.',
             'Design and permit application with the town.',
             'Moisture work, rim joist sealing and any egress cut.',
             'Framing, foam board insulation and fire blocking.',
             'Rough electrical, plumbing and heat, then inspections.',
             'Drywall, ceilings, flooring, trim and paint.',
             'Final inspection and walkthrough with you.'],
            ['Site visit, moisture readings and an itemized estimate.',
             'Layout, selections and permits.',
             'Drainage, sump or dehumidifier work where needed.',
             'Rigid foam on the foundation, then framing.',
             'Wiring, plumbing and heating rough-in with inspections.',
             'Walls, ceilings, floors, doors and built-ins.',
             'Final sign-off and a room-by-room walkthrough.'],
        ],
        'process_close_variants': [
            'Most {City} basements take about 6 to 10 weeks once the permit is issued.',
            'Plan on roughly 6 to 10 weeks for a {City} basement after permits, longer with a bathroom or egress window.',
            'A typical {City} basement runs about 6 to 10 weeks from permit to final walkthrough.',
        ],
        'materials_h2': 'Materials that hold up below grade in {City}',
        'materials_p_variants': [
            'A {City} basement sits against cold, damp concrete or stone, so every material is chosen to handle humidity without growing mold.',
            'Below-grade rooms in {County} County deal with cool foundations and seasonal humidity, so the wall, floor and ceiling materials are picked for that.',
            'Because a {City} basement is partly underground, the assembly is built for moisture first and looks second.',
        ],
        'materials_bullets_variants': [
            ['Rigid foam board against the foundation, not fiberglass on concrete.',
             'Pressure-treated bottom plates and a capillary break.',
             'Mold-resistant drywall in damp-prone areas.',
             'Waterproof luxury vinyl plank flooring.'],
            ['Foam insulation sealed at seams and the rim joist.',
             'Treated sill plates where framing meets the slab.',
             'Moisture-tolerant board around baths and utility areas.',
             'Floating, waterproof floors over a proper underlayment.'],
            ['Continuous foam insulation on foundation walls.',
             'Sealed and insulated rim joists.',
             'Drywall rated for humidity where needed.',
             'Vinyl plank or tile instead of solid wood on concrete.'],
        ],
        'signs_h2': 'Signs a {City} basement is ready to finish',
        'signs_p': 'A few clear signs it is time to turn a {City} basement into living space:',
        'signs_bullets_variants': [
            ['The family has outgrown the main floor.',
             'The basement stays dry after heavy rain.',
             'You need a home office, gym or guest room.',
             'Storage has taken over a space that could be used.',
             'You want more living space without an addition.'],
            ['Kids need a playroom away from the living room.',
             'Moisture is under control, or you are ready to fix it.',
             'Working from home needs a quiet, separate room.',
             'Relatives visit often and need a place to stay.',
             'A dated finished basement needs a full redo.'],
            ['The house feels small but the lot has no room to build out.',
             'The basement has good height and a dry floor.',
             'You want a media room, bar or gym.',
             'An older finished basement smells damp or looks tired.',
             'You plan to sell and want more usable square footage.'],
        ],
        'scope_h2': 'What a full {City} basement finishing project covers',
        'scope_bullets_variants': [
            ['Moisture control, insulation and framing planned together.',
             'Electrical, lighting, heat and, if needed, a bathroom.',
             'Drywall, ceilings, flooring, trim, doors and paint.'],
            ['A dry, insulated envelope before any finish goes in.',
             'Wiring, heat and plumbing roughed in and inspected.',
             'Finished walls, floors, built-ins and lighting.'],
            ['Foundation check, sealing and insulation first.',
             'Permitted electrical, plumbing and egress where needed.',
             'Finish work that matches the rest of the home.'],
        ],
        'photos_h2': 'Finished basement photos for {City} homeowners',
        'photos_p': 'Real DeFaria basements, so {City} homeowners can see the finish level before requesting an estimate.',
        'areas_h2': 'Basement finishing across {City} neighborhoods',
        'areas_p': 'DeFaria Construction finishes basements across {City} and nearby {County} County towns, with enough local context on this page to decide whether we are the right fit before you call.',
        'related_p': 'Compare the full basement finishing guide, the county service area and other {City} services. Each link points to a live page with its own purpose.',
        'scope_link': ('../../../pages/finish-basements/', 'Basement finishing contractors in Massachusetts', 'View page'),
        'blog_link': ('../../../blog/basement-finishing-cost-massachusetts/', 'Basement finishing cost in Massachusetts (2026)', 'Read the guide'),
        'sibling': 'remodeling',
        'sibling_label': '{City} home remodeling',
        'extra_sections': [
            {'eyebrow': 'Moisture', 'theme': 'a dry basement', 'h2': 'Keeping a {City} basement dry before it is finished',
             'paras_variants': [
                 ['Water is the reason most finished basements fail, so every {City} project starts with a moisture check: grading and gutters outside, cracks and old window wells in the foundation, the sump if there is one, and the humidity after a rain.',
                  'Because {constraint}, older foundations here may be stone, block or early poured concrete, and each behaves differently. We fix active water problems first and price them openly, because new drywall over a wet wall only hides the problem.'],
                 ['A finished basement in {City} is only as good as the foundation behind it. Before framing we look at how water reaches the walls, how the floor drains and whether the space needs a sump, a backup pump or a properly sized dehumidifier.',
                  'In {County} County, spring thaw and heavy fall rains test every basement. If a {City} basement leaks or stays damp, drainage comes first and finish work second.'],
                 ['The first visit to a {City} basement is about water, not paint colors. Gutters, downspouts, grading, foundation cracks, the sump and relative humidity all tell us what the walls will face after the room is finished.',
                  'We also recommend a radon test before a basement becomes living space, since many New England homes benefit from mitigation, and it is simplest to add while the space is still open.'],
             ],
             'bullets_variants': [
                 ['Grading, gutters and downspouts checked outside.',
                  'Foundation cracks and penetrations sealed.',
                  'Sump and backup pump where needed.',
                  'Dehumidifier sized for the finished space.'],
                 ['Moisture readings on walls and slab.',
                  'Drainage or waterproofing priced separately and openly.',
                  'Radon test recommended before finishing.',
                  'A capillary break between slab and framing.'],
             ]},
            {'eyebrow': 'Insulation', 'theme': 'insulated basement walls', 'h2': 'Insulating {City} basement walls the right way',
             'paras_variants': [
                 ['Fiberglass pressed against cold concrete traps moisture, so {City} basements get rigid foam board against the foundation, sealed at the seams, with framing built inside it.',
                  'The Massachusetts energy code for our climate zone calls for basement walls insulated to roughly R-15 of continuous insulation or R-19 in the cavity, and foam must be covered with a thermal barrier such as half-inch drywall.'],
                 ['A warm basement depends on the layer behind the drywall. We use continuous foam on the foundation walls in {City}, seal and insulate the rim joist, and fire-block the framing where the code requires it.',
                  'That assembly keeps condensation off the framing and makes the room feel like the rest of the house, not like a cellar with carpet.'],
                 ['The rim joist, where the house sits on the foundation, is one of the leakiest spots in older {County} County homes. In a {City} basement we seal and insulate it first, then cover the foundation with rigid foam before framing.',
                  'Foam is always covered with a code-approved thermal barrier, and the result is a lower level that holds heat through a Massachusetts winter.'],
             ]},
            {'eyebrow': 'Egress and code', 'theme': 'basement safety', 'h2': 'Egress windows, ceilings and code for a {City} basement',
             'paras_variants': [
                 ['Any basement bedroom in {City} needs an emergency escape opening: a window with at least 5.7 square feet of clear opening, at least 20 inches wide and 24 inches high, with the sill no more than 44 inches off the floor, plus a well you can climb out of.',
                  'Habitable basement rooms also need a finished ceiling height of about 7 feet, with some allowance for beams and ducts, plus smoke and carbon monoxide alarms where the code requires them.'],
                 ['Code shapes a {City} basement more than people expect. Bedrooms need an egress window and well, ceilings need enough height for living space, and stairs, alarms and fire blocking all have to pass inspection.',
                  '{permit_line}'],
                 ['If you want a guest room or a teenager\'s room in a {City} basement, plan the egress window from the start. Cutting the foundation and setting a code-size window and well is far easier before the walls are finished.',
                  'We measure ceiling height at the first visit, since ducts and beams decide whether a drywall ceiling, soffits or painted open joists make the most sense.'],
             ],
             'bullets_variants': [
                 ['Egress window and well for every basement bedroom.',
                  'About 7 feet of finished ceiling height for living space.',
                  'Smoke and carbon monoxide alarms.',
                  'Building, electrical and plumbing permits and inspections.'],
                 ['Code-size egress opening with sill under 44 inches.',
                  'Soffits or open joists to protect ceiling height.',
                  'Safe stairs with handrails and lighting.',
                  'Inspections before the walls close.'],
             ]},
            {'eyebrow': 'Bathrooms', 'theme': 'a basement bathroom', 'h2': 'Adding a bathroom to a {City} basement',
             'paras_variants': [
                 ['A bathroom turns a {City} basement into a real suite. If the main drain sits below the new fixtures, they drain by gravity; if not, a sewage ejector pump or an up-flush system does the work without breaking much of the slab.',
                  'A new basement bathroom usually adds about $25,000 to $55,000, depending on how much concrete is opened and the fixtures you choose. Ventilation to the outside and moisture-resistant walls are part of every one we build.'],
                 ['Most families who finish a {City} basement ask about a bathroom. The deciding factor is the depth of the main drain: below the fixtures means gravity drainage, above them means an ejector pump.',
                  'Either way, a basement bath needs a licensed plumber, a plumbing permit, an exhaust fan vented outside and waterproofing at the shower. Budget roughly $25,000 to $55,000 for a new one.'],
                 ['Planning a bathroom early saves money in a {City} basement, because the drain, vent and supply lines are laid out before the floor and walls are finished.',
                  'We coordinate the licensed plumbing, the permit and the inspections, and finish the bathroom with the same tile and trim quality as the rest of the house.'],
             ]},
            {'eyebrow': 'Ideas', 'theme': 'ways to use the space', 'h2': 'Popular ways {City} families use a finished basement',
             'paras_variants': [
                 ['The best {City} basements are planned around one or two clear uses, so the lighting, outlets and layout support them from day one.'],
                 ['Before design starts, we ask how the family will use the {City} basement on a normal Tuesday night, because that decides the layout.'],
                 ['A {City} basement can solve the space problem a house has: room for kids, guests, work or storage, depending on the stage of life.'],
             ],
             'bullets_variants': [
                 ['Family room or home theater.',
                  'Home office with a door and daylight.',
                  'Home gym with durable flooring.',
                  'Guest suite with egress and a bathroom.',
                  'Playroom with built-in storage.'],
                 ['Media room with recessed lighting on dimmers.',
                  'Wet bar for entertaining.',
                  'Quiet office away from the household.',
                  'In-law space with a full bathroom.',
                  'Organized storage and laundry kept separate.'],
             ]},
            {'eyebrow': 'Timing', 'theme': 'planning the project', 'h2': 'Why fall and winter suit a {City} basement project',
             'paras_variants': [
                 ['Basement work is indoors, so snow and cold rarely slow it down. Starting a {City} basement in the fall usually means the room is ready for the holidays or by spring.',
                  'Searches for basement finishing contractors in Massachusetts peak in September and October for that reason, and the permit and design steps take a few weeks, so booking the walkthrough early helps.'],
                 ['Many {City} families book exterior projects for the warm months and the basement for the cold ones. It keeps the crew busy indoors when the weather turns and frees the summer for decks and siding.',
                  'If you want a finished basement before spring, the time to measure, design and permit is in the fall and early winter.'],
                 ['A {City} basement is a natural winter project: the work happens below the living space, the house stays heated, and the dust is kept behind barriers while the family lives upstairs.',
                  'Planning now also gives time to decide on a bathroom, egress window or built-ins before the walls are framed.'],
             ]},
        ],
        'exp_tail': 'the {City} basement page is written around real moisture control, insulation and finish work, not a town name dropped into a template.',
        'quotes': [
            'our {City} basement finally feels like part of the house, warm and dry.',
            'DeFaria handled the {City} basement from the moisture check to the trim.',
            'the {City} basement went from storage to the room we use every day.',
            'they explained every step of the {City} basement before the walls went up.',
        ],
        'faq': [
            ('How much does basement finishing cost in {City}?',
             'Most {City} basements run about $35 to $90 per square foot, so a typical 700 to 900 square foot basement lands roughly between $30,000 and $75,000. Moisture work, a bathroom or an egress window add to that. DeFaria gives a fixed, itemized estimate at the walkthrough.'),
            ('Do I need a permit to finish a basement in {City}?',
             'Yes. Turning a basement into living space needs a building permit, and electrical and plumbing work need their own permits by licensed trades. {permit_line}'),
            ('How long does it take to finish a basement in {City}?',
             'Most {City} basements take about 6 to 10 weeks once the permit is issued, longer with a bathroom, an egress window or moisture repairs.'),
            ('Do I need an egress window in my {City} basement?',
             'Any basement bedroom needs a code-size emergency escape window and well. A family room, office or gym without a sleeping room usually does not, but alarms, stairs and ceiling height still have to meet code.'),
            ('Can you finish a {City} basement that gets water?',
             'Only after the water problem is fixed. We check grading, gutters, cracks, the sump and humidity first, and price any drainage or waterproofing separately and openly.'),
            ('Is DeFaria Construction licensed and insured?',
             'Yes. DeFaria Construction is a licensed and insured contractor with an A+ BBB rating and verified Google reviews, and every {City} basement is owner-led by Luiz DeFaria.'),
        ],
    }
