# -*- coding: utf-8 -*-
# Avaliacoes REAIS do Google (DeFaria Construction, Lynn MA). Fonte: Serper/Google. Coletado 2026-09-13.
REVIEW_RATING = 5.0
REVIEW_COUNT = 15
REVIEWS = [
    {'author': 'Allanderson Amorim', 'rating': 5, 'date': '2 weeks ago', 'text': 'Excellent work! I’m extremely happy with the results of my bathroom. Defaria Construction did an amazing job and was very professional, careful, and detail-oriented throughout the entire project. The workmanship and finishing touches were outstanding. You can really tell when a company takes pride…'},
    {'author': 'Jonathan Parham (Brent)', 'rating': 5, 'date': 'a month ago', 'text': 'I highly recommend Luiz as a contractor. When my spouse and I became first-time homebuyers, we hired him for a substantial remodel: painting walls throughout, refinished hardwood flooring and new tiles, new ceilings, and some carpentry. Luiz genuinely listened to our priorities when crafting the…'},
    {'author': 'Chris Gaius', 'rating': 5, 'date': 'a month ago', 'text': 'Luiz has been doing construction for us for close to 20 years. Large jobs are small. He does excellent work and we’re always very pleased with it. His quotes are always very reasonable. I would highly recommend him.'},
    {'author': 'Lauren Verra', 'rating': 5, 'date': 'a month ago', 'text': 'My husband and I are so grateful for the beautiful work Luis did to get our home move-in ready. We had a newborn and a tight move-in window, and Luis went above and beyond to get everything done in time. He helped us with multiple projects including building a gate, repairing walls/doors…'},
    {'author': 'Ira Blieden', 'rating': 5, 'date': 'a year ago', 'text': 'Luiz and subcontractors do great work. DeFaria Carpentry completed 2 bathroom renovations and we will be starting on a kitchen renovation in the fall. I highly recommend DeFaria Carpentry.'},
    {'author': 'Andre Vieira', 'rating': 5, 'date': '5 months ago', 'text': 'I have work with Defaria Carpenter in my project, and they give me the best experience I never have with another contractor. Thank for the great job you guys done at my house.'},
    {'author': 'John Lopes', 'rating': 5, 'date': '11 months ago', 'text': 'Wow! I couldn’t believe where I would be without Luiz. He completely transformed our kitchen and bathroom over the last year. My wife can’t get over the work he did. Would definitely recommend'},
    {'author': 'Evelyn Balduino', 'rating': 5, 'date': 'a year ago', 'text': 'Very professional, efficient and thorough. They are extremely attentive to details and are fast-paced. Best contractor I’ve worked with!'},
    {'author': 'Mark Ottesen', 'rating': 5, 'date': '2 weeks ago', 'text': 'Luiz has done many projects, from major renovations to minor repairs, for us in multiple homes over the last ten years. He and his company always do excellent and timely work. I would recommend him any time.'},
    {'author': 'Sue', 'rating': 5, 'date': '3 weeks ago', 'text': 'Luiz’s work is fabulous. Luiz renovated two bathrooms and our kitchen. Each step in the process moved along quickly and we finished earlier than expected. The crew was always pleasant to be around. We are very pleased with the quality of everything that Luiz did, and the price was reasonable. We…'},
    {'author': 'Kenneth Smith', 'rating': 5, 'date': 'a month ago', 'text': 'DeFaria Construction completed a full remodel of our master bathroom to our great satisfaction. Demolition down to the studs and subfloor was completed quickly. Plumbing changes and waterproof underlayment were quickly installed. Tiling of the floor and shower were beautifully done. Installation of…'},
    {'author': 'Pete Kamm', 'rating': 5, 'date': 'a month ago', 'text': 'Luiz and team did amazing work and were a pleasure to work with!'},
    {'author': 'Lisa Krikorian', 'rating': 5, 'date': 'a month ago', 'text': 'Extremely happy that I went with DeFaria Construction to renovate our half bathroom. What I appreciated most about working with Luiz is that him and his crew were honest, reliable and they really cared about the details that were important to me! Everyday they came as scheduled and every evening…'},
    {'author': 'Ron Mansur', 'rating': 5, 'date': 'a month ago', 'text': 'We used DeFaria Construction twice, once for a gut remodel of a condo unit and the other for a basement and garage upgrade. They are very professional, reasonably priced, do a great job, stick to their timelines and leave the work area totally clean at the end of every day. I highly recommend Luiz…'},
    {'author': 'Joanne Tingle - Makena', 'rating': 5, 'date': 'a month ago', 'text': 'Beautiful full bathroom installment!! I love it!!'},
]
